### PR TITLE
added Auto Youtube Uploading Feature 

### PR DESCRIPTION
**Pull request by 1NoobDev**
Added automatic uploading to Youtube via YouTube Data API v3. 
gpt.py is expanded to also generate the title, description and keywords for the videos.

	modified:   Backend/gpt.py
	modified:   Backend/main.py
	modified:   Backend/search.py
	new file:   Backend/youtube.py
	modified:   README.md
	modified:   requirements.txt

### CODE REVIEW

**Comment by FujiwaraChoki** [comment]
Amazing, just one thing - could you add it as a toggle in the frontend, and then send it with the request?

Just so the user has the **option** to upload it to YouTube, and isn't forced to. Other than that, thanks for this!

**Comment by 1NoobDev** [comment]
I've added the toggle button to the frontend :)

**Comment by FujiwaraChoki** [comment]
Why did you close?

**Comment by 1NoobDev** [comment]
I think by accident when cleaning the merge conflicts.. New PR created :)

**Comment by FujiwaraChoki** [comment]
Just merged - thanks for this!

**Comment by Skeyelab** [comment]
@FujiwaraChoki did something happen to this code?  I cannot find it in the main branch

**Comment by WaterPheonix196** [comment]
Nope. Its still there

**Comment by Skeyelab** [comment]
@WaterPheonix196 [https://github.com/FujiwaraChoki/MoneyPrinter/tree/main/Backend](https://github.com/FujiwaraChoki/MoneyPrinter/tree/main/Backend)

Where is `Backend/youtube.py`?

**Comment by FujiwaraChoki** [comment]
> @FujiwaraChoki did something happen to this code? I cannot find it in the main branch

It had some issues with it - I'm going to be implementing this on my own using Selenium some time in the near future.
I still appreciate the hard work guys ❤️

**Comment by Skeyelab** [comment]
@FujiwaraChoki thanks for the update.  I thought I was going crazy.  In the meantime, can we bring back `generate_metadata` and output that info in the backend console?

**Comment by 1NoobDev** [comment]
> > @FujiwaraChoki did something happen to this code? I cannot find it in the main branch
> 
> It had some issues with it - I'm going to be implementing this on my own using Selenium some time in the near future. I still appreciate the hard work guys ❤️

What issues did you have with it? I'm happy to assist and resolve, especially because the youtube.py didn't really use any of the existing functions. 

@FujiwaraChoki here's the code for generate_metadata:

```
# gpt.py
def generate_metadata(video_subject: str, script: str) -> Tuple[str, str, List[str]]:  
    """  
    Generate metadata for a YouTube video, including the title, description, and keywords.  
  
    Args:  
        video_subject (str): The subject of the video.  
        script (str): The script of the video.  
  
    Returns:  
        Tuple[str, str, List[str]]: The title, description, and keywords for the video.  
    """  
  
    # Build prompt for title  
    title_prompt = f"""  
    Generate a catchy and SEO-friendly title for a YouTube shorts video about {video_subject}.  
    """  
  
    # Generate title  
    title_response = g4f.ChatCompletion.create(  
        model=g4f.models.gpt_35_turbo_16k_0613,  
        messages=[{"role": "user", "content": title_prompt}],  
    )  
  
    # Extract title from response  
    title = title_response.strip()  # Assuming title_response is a string  
  
    # Build prompt for description  
    description_prompt = f"""  
    Write a brief and engaging description for a YouTube shorts video about {video_subject}.  
    The video is based on the following script:  
    {script}  
    """  
  
    # Generate description  
    description_response = g4f.ChatCompletion.create(  
        model=g4f.models.gpt_35_turbo_16k_0613,  
        messages=[{"role": "user", "content": description_prompt}],  
    )  
  
    # Extract description from response  
    description = description_response.strip()  # Assuming description_response is a string  
  
    # Generate keywords  
    keywords = get_search_terms(video_subject, 6, script)  # Assuming you want 6 keywords  
  
    return title, description, keywords  
```


```
# main.py
            # Choose the appropriate category ID for your videos  
            video_category_id = "28"  # Science & Technology  
            privacyStatus = "private"  # "public", "private", "unlisted"  
            video_metadata = {  
                'video_path': os.path.abspath(f"../temp/{final_video_path}"),  
                'title': title,  
                'description': description,  
                'category': video_category_id,  
                'keywords': ",".join(keywords),  
                'privacyStatus': privacyStatus,  
            }  
```

**Comment by FujiwaraChoki** [comment]
> > > @FujiwaraChoki did something happen to this code? I cannot find it in the main branch
> > 
> > 
> > It had some issues with it - I'm going to be implementing this on my own using Selenium some time in the near future. I still appreciate the hard work guys ❤️
> 
> What issues did you have with it? I'm happy to assist and resolve, especially because the youtube.py didn't really use any of the existing functions.
> 
> @Skeyelab here's the code for generate_metadata:
> 
> ```
> # gpt.py
> def generate_metadata(video_subject: str, script: str) -> Tuple[str, str, List[str]]:  
>     """  
>     Generate metadata for a YouTube video, including the title, description, and keywords.  
>   
>     Args:  
>         video_subject (str): The subject of the video.  
>         script (str): The script of the video.  
>   
>     Returns:  
>         Tuple[str, str, List[str]]: The title, description, and keywords for the video.  
>     """  
>   
>     # Build prompt for title  
>     title_prompt = f"""  
>     Generate a catchy and SEO-friendly title for a YouTube shorts video about {video_subject}.  
>     """  
>   
>     # Generate title  
>     title_response = g4f.ChatCompletion.create(  
>         model=g4f.models.gpt_35_turbo_16k_0613,  
>         messages=[{"role": "user", "content": title_prompt}],  
>     )  
>   
>     # Extract title from response  
>     title = title_response.strip()  # Assuming title_response is a string  
>   
>     # Build prompt for description  
>     description_prompt = f"""  
>     Write a brief and engaging description for a YouTube shorts video about {video_subject}.  
>     The video is based on the following script:  
>     {script}  
>     """  
>   
>     # Generate description  
>     description_response = g4f.ChatCompletion.create(  
>         model=g4f.models.gpt_35_turbo_16k_0613,  
>         messages=[{"role": "user", "content": description_prompt}],  
>     )  
>   
>     # Extract description from response  
>     description = description_response.strip()  # Assuming description_response is a string  
>   
>     # Generate keywords  
>     keywords = get_search_terms(video_subject, 6, script)  # Assuming you want 6 keywords  
>   
>     return title, description, keywords  
> ```
> 
> ```
> # main.py
>             # Choose the appropriate category ID for your videos  
>             video_category_id = "28"  # Science & Technology  
>             privacyStatus = "private"  # "public", "private", "unlisted"  
>             video_metadata = {  
>                 'video_path': os.path.abspath(f"../temp/{final_video_path}"),  
>                 'title': title,  
>                 'description': description,  
>                 'category': video_category_id,  
>                 'keywords': ",".join(keywords),  
>                 'privacyStatus': privacyStatus,  
>             }  
> ```
> 
> or just look into my repo, and take the code from there :)

The `generate_video` function was updated to just give 1 parameter, when it needed 3, causing it to throw an [error](https://github.com/FujiwaraChoki/MoneyPrinter/issues/33).

**Comment by 1NoobDev** [comment]
That's great; the youtube PR doesn't touch the `generate_video`, nor the `generate_subtitles` function mentioned in #33 .. It only uses the `final_video_path` to take the video result for the upload, `video_subject` to generate the metadata and `get_search_terms` for metadata keywords. After inspecting the repo history, I find that the generate_subtitles was edited in the commit on #13 ; from  . I will create a new PR with the yt uploading functions in the latest codebase later today if you allow me :)

**Comment by FujiwaraChoki** [comment]
Oh... I apologize I didn't see that. Sure please go ahead and do that!

**Comment by 1NoobDev** [comment]
No worries, I'm happy to add it into your repo again :)

**Pull request closed without merging**
