### PR TITLE
feat: Using videos from TikTok

### PR DESCRIPTION
**Pull request by jhl8041**
Using videos from TikTok using TikTok API.
When TIKTOK_MS_CODE env exists, it uses videos from Tiktok instead of Pexels

TikTok API: https://github.com/davidteather/TikTok-Api

### CODE REVIEW

**Comment by WaterPheonix196** [comment]
Good changes but do the same thing I did and keep the format of video.py and maybe a few others from this, 

```python
import requests
import srt_equalizer
import assemblyai as aai
import asyncio
import random
``` 

To this: 
```python
import asyncio
import random
import requests
import srt_equalizer
import assemblyai as aai
``` 


Aka keep the shortest at the start and longest at the end.

**Comment by radry** [comment]
What is the copyright situation with tiktok videos? No point in using them if the resulting video gets a strike when uploaded...

**Comment by FujiwaraChoki** [comment]
@jhl8041 Did you test whether it works? Also, somehow needs to make sure there aren't pre-made subtitles on the TikToks. That would cause an irritating overlay, maybe use tesseract OCR, or something in that direction.

**Comment by Ashes47** [comment]
Also can we not remove pexel and let user choose where to get videos from?

**Comment by radry** [comment]
@Ashes47 
Where would they get it from? The whole point of this program is to do everything automatically.

**Comment by Ashes47** [comment]
it's also a search on tiktok?
🤔

**Comment by jhl8041** [comment]
@Ashes47 
couldn't find search feature on TikTok API so I used generating hashtag to search 🫠

**Comment by jhl8041** [comment]
@radry 
I'm not quite sure with copyrights with TikTok, but I think it wouldn't be that strict if their music is not included..? Not quite sure though..

**Comment by jhl8041** [comment]
> @jhl8041 Did you test whether it works? Also, somehow needs to make sure there aren't pre-made subtitles on the TikToks. That would cause an irritating overlay, maybe use tesseract OCR, or something in that direction.

@FujiwaraChoki 
I'll come up with the solution to avoid overlay subtitles and request PR again. Thanks for the direction

**Pull request closed without merging**
