### PR TITLE
Refactor docker setup

### PR DESCRIPTION
**Pull request by RicardoMonteiroSimoes**
Refactors docker setup to:
- use values defined in the `.env` file
- mounts the `Backend` and `Frontend` folders, so that you can work on the code without having to rebuild the images
- changes the image to one that requires less space
- cleans up the docker file itself

Now only a change in the `requirements.txt` requires a rebuild

### CODE REVIEW

**Review by FujiwaraChoki — COMMENTED** [review]
Please add OpenAI API Key to the env's as well

**Comment by RicardoMonteiroSimoes** [comment]
> Please add OpenAI API Key to the env's as well

Added it

**Comment by iStorry** [comment]
> Refactors docker setup to:
> 
> * use values defined in the `.env` file
> * mounts the `Backend` and `Frontend` folders, so that you can work on the code without having to rebuild the images
> * changes the image to one that requires less space
> * cleans up the docker file itself
> 
> Now only a change in the `requirements.txt` requires a rebuild

It's good for localhost but not for the server this means every time you change something and you need to deploy that on the server first you've to pull the code from git and then docker compose up

**Comment by RicardoMonteiroSimoes** [comment]
> > Refactors docker setup to:
> 
> > 
> 
> > * use values defined in the `.env` file
> 
> > * mounts the `Backend` and `Frontend` folders, so that you can work on the code without having to rebuild the images
> 
> > * changes the image to one that requires less space
> 
> > * cleans up the docker file itself
> 
> > 
> 
> > Now only a change in the `requirements.txt` requires a rebuild
> 
> 
> 
> It's good for localhost but not for the server this means every time you change something and you need to deploy that on the server first you've to pull the code from git and then docker compose up 
> 
> 
> 
> Also I am not able to see ImageMagick build command. Since you've removed this
> 
> ```sh
> 
> RUN sh ./ImageMagick-7.1.0-31/configure --prefix=/usr/local --with-bzlib=yes --with-fontconfig=yes --with-freetype=yes --with-gslib=yes --with-gvc=yes --with-jpeg=yes --with-jp2=yes --with-png=yes --with-tiff=yes --with-xml=yes --with-gs-font-dir=yes && \
> 
>     make -j && make install && ldconfig /usr/local/lib/
> 
> ```
> 
> 
> 
> You will not be able to access the `/usr/local/bin/magick`
> 
> 

No, that RUN part is still there, I didnt remove it.

I mean yeah, sure, you need to git pull, but if you update the image you also need to pull in the new one and then compose up? I guess if you want to offer both, two images can be made, as the live restart this offers is quite valuable for development

**Pull request merged**
