### PR TITLE
Pull request to make scripts easier to see.

### PR DESCRIPTION
**Pull request by WaterPheonix196**
Changes: 
f-string optimizations 
Grammar fixes

### CODE REVIEW

**Comment by WaterPheonix196** [comment]
Edit: found error: ChatgptDemoAi: ClientResponseError: 400, message='Can not decode content-encoding: brotli (br). Please install `Brotli`', url=URL('https://chat.chatgptdemo.ai/wp-json/mwai-ui/v1/chats/submit')

Solution: add brotli to requirements

**Review by FujiwaraChoki — CHANGES_REQUESTED** [review]
Try to keep the format of `import` statements.

First are the `import` statements,
then the `from xx import yy``.

Also, sort by length.

Other than that it looks good!

**Comment by WaterPheonix196** [comment]
alright, ill fix

**Comment by FujiwaraChoki** [comment]
> alright, ill fix
> 
> 
> 
> Edit: fixed, changed requirements to have brotli. sry I'm new to the git pull requests, do I have to mark changes fulfilled or does it just work.

Mark it as fulfilled

**Pull request merged**
