### PR TITLE
Check empty environment variables & Reformat .env.example

### PR DESCRIPTION
**Pull request by Gudauu**
# .env.example
* Removed all inline comments due to the observation that `load_dotenv()` is not parsing inline comments correctly. For instance in the old `.env.example`:
```
TIKTOK_SESSION_ID="" # TikTok Session ID
```
`TIKTOK_SESSION_ID` will evaluates to: `"" # TikTok Session ID`, making it hard to do validity check.
* Now all comments are on another line.
```
# TikTok Session ID
# Obtain your session ID by logging into TikTok and copying the sessionid cookie.
TIKTOK_SESSION_ID=""
```
# Backend/utils.py
* Add function `check_env_vars()` which exits the program if any required environment variables(`PEXELS_API_KEY`, `TIKTOK_SESSION_ID`, `IMAGEMAGICK_BINARY`) is missing.

# Backend/main.py
* Call `check_env_vars()` before importing any modules that uses the above three env variables.

### CODE REVIEW

**Comment by Ashes47** [comment]
TIKTOK is also optional API.

**Comment by Gudauu** [comment]
> TIKTOK is also optional API.

You're right. Seems `TIKTOK_SESSION_ID` hasn't really been used
But it still shows up as "required" in `EnvironmentVariables.md`
Preempt or obsolete requirement??

**Comment by FujiwaraChoki** [comment]
Nice pr, merged.

**Comment by Ashes47** [comment]
TIKTOK is also optional API.

This should be updated.

**Pull request merged**
