### PR TITLE
Improve cropping

### PR DESCRIPTION
**Pull request by radry**
Crops a vertical slide in 9:16 aspect ratio exactly in the height of the given video clip and only resizes it afterwards. This greatly improves quality as now it doesn't crop a strange zoomed in portion of the video.

Also I improved the detection of vertical video slightly.

### CODE REVIEW

**Comment by FujiwaraChoki** [comment]
Have you tested if it works as intended?

**Comment by radry** [comment]
Yes :) I test all my pull requests

**Comment by xDope7137** [comment]
Adding "&orientation=portrait" in the pexels API made it so it only fetches vertical videos.

It works in mostly all situation, but if the topic is very unique, it cannot find lot of vertical videos.

**Comment by radry** [comment]
@xDope7137 
I know but it limits the results we get. In the future we could implement a simple checkbox in the frontend to select if we want to limit the search to vertical only videos.

**Pull request merged**
