### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by V4M0N0S**
Added solution for linux servers imagemagick.

### CODE REVIEW

**Comment by V4M0N0S** [comment]
Verified in discord.

**Comment by bbrooks870** [comment]
Hi can you Please check the issue regarding this

https://github.com/FujiwaraChoki/MoneyPrinter/issues/89

**Comment by FujiwaraChoki** [comment]
Possibly turn into an FAQ Section with the most asked questions - including this one.

**Comment by V4M0N0S** [comment]
> Possibly turn into an FAQ Section with the most asked questions - including this one.

ppl want run it on linux server with automation, this police error is more then a faq thing.

**Comment by V4M0N0S** [comment]
> Hi can you Please check the issue regarding this
> 
> #89

related, check police.

**Comment by bbrooks870** [comment]
Hi ALL ,

This fixed the problem of Policy

sed -i '/<policy domain="path" rights="none" pattern="@\*"/d' /etc/ImageMagick-6/policy.xml

**Comment by BrettFraley** [comment]
Thanks @V4M0N0S  for opening the issue and pull request. I'm on Ubuntu 23.10 and getting ImageMagick 8 built and installed was :thinking: , fun_

**Comment by FujiwaraChoki** [comment]
> > Possibly turn into an FAQ Section with the most asked questions - including this one.
> 
> 
> 
> ppl want run it on linux server with automation, this police error is more then a faq thing.

Then this will not be merged.

**Pull request closed without merging**
