### PR TITLE
Add Gemini Pro Model

### PR DESCRIPTION
**Pull request by tatphuong**
Add Gemini Pro Model (API FREE)
Link get API key: https://makersuite.google.com/app/apikey

### CODE REVIEW

**Comment by FujiwaraChoki** [comment]
Add relevant documentation in ENV.md and README.md.

**Comment by tatphuong** [comment]
> Add relevant documentation in ENV.md and README.md.

Document has been added to env.md

**Comment by FujiwaraChoki** [comment]
Great, did you test?

**Comment by llIllIllllIIIlllllll** [comment]
.env
GOOGLE_API_KEY="1q2w3e4r"

/Frontend/intex.html
 <option value="gemini-pro">gemini-pro</option>
 
 gpt.py
 import google.generativeai as genai
 
 elif ai_model == 'gemini-pro':
        GOOGLE_API_KEY=os.getenv('GOOGLE_API_KEY')
        genai.configure(api_key=GOOGLE_API_KEY)
        model = genai.GenerativeModel('gemini-pro')
        response = model.generate_content(prompt).text

**Comment by tatphuong** [comment]
> Great, did you test?

Yes, I have tested it, and I am currently using it.

**Comment by FujiwaraChoki** [comment]
Merged - thanks!

**Pull request merged**
